### ISSUE TITLE
Error with setting up SSH connection

### ISSUE THREAD

**Issue by captenmasin** [beyondcode/invoker-community#67]
OS: Big Sur 11.1
Invoker version: 2.0.1

Getting an error when setting up a new SSH connection
```
Error: Error while signing data with privateKey: error:06000066:public key 
routines:OPENSSL_internal:DECODE_ERROR
```

My SSH details are definitely correct

**Comment by FliloSolutions** [comment]
Possible work around.

I had the same issue in windows and converted the private key file to openSSH format using puttygen and it worked.

**Comment by zembrowski** [comment]
@captenmasin Had the same issue on macOS. Converting my OpenSSH key to PEM solved this.

`ssh-keygen -p -m PEM -f ~/.ssh/private_key`

**Comment by mpociot** [comment]
This error should've been resolved in the latest version of Invoker.

**Comment by zembrowski** [comment]
This error is still present with some keys (probably generated before a certain version of OpenSSH).

[Generating new keys](https://blog.g3rt.nl/upgrade-your-ssh-keys.html) solves this issue.

(Error reproducible with 4096-bit RSA keys created in 2019. Not reproducible with newly created keys. Tested with Invoker 2.4 on macOS 11.2.3 and macOS 10.15.7)

**Comment by ndberg** [comment]
Can confirm this, my old RSA 2048 SHA256  key did not work (Invoker 2.9.0).

Created a new EDDSA key, and now it works.

The error I got before was:
`Connection :: error Error: All configured authentication methods failed`
